import Foundation

/// A small built-in list of common emoji, used only when `CatalogIndex`'s
/// bundled Twemoji pack isn't available in this build (e.g. the AssetPacks
/// resource directory isn't wired into the running app bundle yet). Each
/// entry carries a couple of plain-English search keywords.
enum EmojiFallbackCatalog {
    struct Entry {
        let character: String
        let keywords: [String]
    }

    static let all: [Entry] = [
        // Faces
        Entry(character: "\u{1F600}", keywords: ["grin", "smile", "happy"]),
        Entry(character: "\u{1F603}", keywords: ["smile", "happy"]),
        Entry(character: "\u{1F604}", keywords: ["smile", "happy"]),
        Entry(character: "\u{1F601}", keywords: ["grin", "smile"]),
        Entry(character: "\u{1F606}", keywords: ["laugh", "happy"]),
        Entry(character: "\u{1F605}", keywords: ["sweat", "laugh"]),
        Entry(character: "\u{1F923}", keywords: ["rofl", "laugh"]),
        Entry(character: "\u{1F602}", keywords: ["laugh", "tears", "lol"]),
        Entry(character: "\u{1F642}", keywords: ["smile", "slight"]),
        Entry(character: "\u{1F643}", keywords: ["upside down", "silly"]),
        Entry(character: "\u{1F609}", keywords: ["wink"]),
        Entry(character: "\u{1F60A}", keywords: ["smile", "blush", "happy"]),
        Entry(character: "\u{1F607}", keywords: ["angel", "innocent"]),
        Entry(character: "\u{1F970}", keywords: ["love", "hearts"]),
        Entry(character: "\u{1F60D}", keywords: ["love", "heart eyes"]),
        Entry(character: "\u{1F929}", keywords: ["star struck", "excited"]),
        Entry(character: "\u{1F618}", keywords: ["kiss", "love"]),
        Entry(character: "\u{1F60B}", keywords: ["yum", "tasty"]),
        Entry(character: "\u{1F61B}", keywords: ["tongue", "playful"]),
        Entry(character: "\u{1F92A}", keywords: ["crazy", "wild"]),
        Entry(character: "\u{1F911}", keywords: ["money", "rich"]),
        Entry(character: "\u{1F917}", keywords: ["hug"]),
        Entry(character: "\u{1F914}", keywords: ["think", "hmm"]),
        Entry(character: "\u{1F610}", keywords: ["neutral"]),
        Entry(character: "\u{1F636}", keywords: ["quiet", "no mouth"]),
        Entry(character: "\u{1F60F}", keywords: ["smirk"]),
        Entry(character: "\u{1F612}", keywords: ["unamused"]),
        Entry(character: "\u{1F644}", keywords: ["eye roll"]),
        Entry(character: "\u{1F62C}", keywords: ["grimace"]),
        Entry(character: "\u{1F60C}", keywords: ["relieved", "calm"]),
        Entry(character: "\u{1F634}", keywords: ["sleep", "zzz"]),
        Entry(character: "\u{1F637}", keywords: ["sick", "mask"]),
        Entry(character: "\u{1F912}", keywords: ["sick", "thermometer"]),
        Entry(character: "\u{1F915}", keywords: ["hurt", "bandage"]),
        Entry(character: "\u{1F922}", keywords: ["nauseated", "sick"]),
        Entry(character: "\u{1F927}", keywords: ["sneeze", "sick"]),
        Entry(character: "\u{1F975}", keywords: ["hot", "heat"]),
        Entry(character: "\u{1F976}", keywords: ["cold", "freezing"]),
        Entry(character: "\u{1F635}", keywords: ["dizzy"]),
        Entry(character: "\u{1F92F}", keywords: ["mind blown", "shock"]),
        Entry(character: "\u{1F60E}", keywords: ["cool", "sunglasses"]),
        Entry(character: "\u{1F913}", keywords: ["nerd", "glasses"]),
        Entry(character: "\u{1F615}", keywords: ["confused"]),
        Entry(character: "\u{1F61F}", keywords: ["worried", "sad"]),
        Entry(character: "\u{1F622}", keywords: ["cry", "sad"]),
        Entry(character: "\u{1F62D}", keywords: ["sob", "cry"]),
        Entry(character: "\u{1F631}", keywords: ["scream", "fear"]),
        Entry(character: "\u{1F621}", keywords: ["angry", "mad"]),
        Entry(character: "\u{1F620}", keywords: ["angry", "mad"]),
        Entry(character: "\u{1F624}", keywords: ["triumph", "steam"]),
        Entry(character: "\u{1F608}", keywords: ["devil", "smiling"]),
        Entry(character: "\u{1F47F}", keywords: ["devil", "angry"]),
        Entry(character: "\u{1F929}", keywords: ["star struck"]),

        // Gestures / hands
        Entry(character: "\u{1F44B}", keywords: ["wave", "hello"]),
        Entry(character: "\u{270B}", keywords: ["hand", "stop"]),
        Entry(character: "\u{1F44C}", keywords: ["ok"]),
        Entry(character: "\u{270C}\u{FE0F}", keywords: ["peace", "victory"]),
        Entry(character: "\u{1F91E}", keywords: ["fingers crossed", "luck"]),
        Entry(character: "\u{1F918}", keywords: ["rock on"]),
        Entry(character: "\u{1F919}", keywords: ["call me"]),
        Entry(character: "\u{1F448}", keywords: ["point left"]),
        Entry(character: "\u{1F449}", keywords: ["point right"]),
        Entry(character: "\u{1F446}", keywords: ["point up"]),
        Entry(character: "\u{1F447}", keywords: ["point down"]),
        Entry(character: "\u{1F44D}", keywords: ["thumbs up", "like", "good"]),
        Entry(character: "\u{1F44E}", keywords: ["thumbs down", "dislike"]),
        Entry(character: "\u{270A}", keywords: ["fist", "punch"]),
        Entry(character: "\u{1F44F}", keywords: ["clap", "applause"]),
        Entry(character: "\u{1F64C}", keywords: ["raised hands", "celebrate"]),
        Entry(character: "\u{1F450}", keywords: ["open hands"]),
        Entry(character: "\u{1F64F}", keywords: ["pray", "please", "thanks"]),
        Entry(character: "\u{1F4AA}", keywords: ["muscle", "strong"]),

        // Body / people
        Entry(character: "\u{1F440}", keywords: ["eyes", "look"]),
        Entry(character: "\u{2764}\u{FE0F}", keywords: ["heart", "love"]),
        Entry(character: "\u{1F9E1}", keywords: ["heart", "orange"]),
        Entry(character: "\u{1F49B}", keywords: ["heart", "yellow"]),
        Entry(character: "\u{1F49A}", keywords: ["heart", "green"]),
        Entry(character: "\u{1F499}", keywords: ["heart", "blue"]),
        Entry(character: "\u{1F49C}", keywords: ["heart", "purple"]),
        Entry(character: "\u{1F5A4}", keywords: ["heart", "black"]),
        Entry(character: "\u{1F90D}", keywords: ["heart", "white"]),
        Entry(character: "\u{1F494}", keywords: ["heart", "broken"]),
        Entry(character: "\u{1F495}", keywords: ["hearts", "love"]),

        // Animals
        Entry(character: "\u{1F436}", keywords: ["dog"]),
        Entry(character: "\u{1F431}", keywords: ["cat"]),
        Entry(character: "\u{1F42D}", keywords: ["mouse"]),
        Entry(character: "\u{1F439}", keywords: ["hamster"]),
        Entry(character: "\u{1F430}", keywords: ["rabbit", "bunny"]),
        Entry(character: "\u{1F98A}", keywords: ["fox"]),
        Entry(character: "\u{1F43B}", keywords: ["bear"]),
        Entry(character: "\u{1F43C}", keywords: ["panda"]),
        Entry(character: "\u{1F428}", keywords: ["koala"]),
        Entry(character: "\u{1F42F}", keywords: ["tiger"]),
        Entry(character: "\u{1F981}", keywords: ["lion"]),
        Entry(character: "\u{1F42E}", keywords: ["cow"]),
        Entry(character: "\u{1F437}", keywords: ["pig"]),
        Entry(character: "\u{1F438}", keywords: ["frog"]),
        Entry(character: "\u{1F435}", keywords: ["monkey"]),
        Entry(character: "\u{1F414}", keywords: ["chicken"]),
        Entry(character: "\u{1F427}", keywords: ["penguin"]),
        Entry(character: "\u{1F426}", keywords: ["bird"]),
        Entry(character: "\u{1F986}", keywords: ["duck"]),
        Entry(character: "\u{1F985}", keywords: ["eagle"]),
        Entry(character: "\u{1F989}", keywords: ["owl"]),
        Entry(character: "\u{1F98B}", keywords: ["butterfly"]),
        Entry(character: "\u{1F41D}", keywords: ["bee"]),
        Entry(character: "\u{1F41E}", keywords: ["ladybug"]),
        Entry(character: "\u{1F422}", keywords: ["turtle"]),
        Entry(character: "\u{1F40D}", keywords: ["snake"]),
        Entry(character: "\u{1F419}", keywords: ["octopus"]),
        Entry(character: "\u{1F980}", keywords: ["crab"]),
        Entry(character: "\u{1F41F}", keywords: ["fish"]),
        Entry(character: "\u{1F42C}", keywords: ["dolphin"]),
        Entry(character: "\u{1F433}", keywords: ["whale"]),
        Entry(character: "\u{1F988}", keywords: ["shark"]),
        Entry(character: "\u{1F434}", keywords: ["horse"]),
        Entry(character: "\u{1F984}", keywords: ["unicorn"]),

        // Food
        Entry(character: "\u{1F34E}", keywords: ["apple"]),
        Entry(character: "\u{1F34C}", keywords: ["banana"]),
        Entry(character: "\u{1F347}", keywords: ["grapes"]),
        Entry(character: "\u{1F353}", keywords: ["strawberry"]),
        Entry(character: "\u{1F349}", keywords: ["watermelon"]),
        Entry(character: "\u{1F34B}", keywords: ["lemon"]),
        Entry(character: "\u{1F34D}", keywords: ["pineapple"]),
        Entry(character: "\u{1F951}", keywords: ["avocado"]),
        Entry(character: "\u{1F345}", keywords: ["tomato"]),
        Entry(character: "\u{1F955}", keywords: ["carrot"]),
        Entry(character: "\u{1F33D}", keywords: ["corn"]),
        Entry(character: "\u{1F35E}", keywords: ["bread"]),
        Entry(character: "\u{1F9C0}", keywords: ["cheese"]),
        Entry(character: "\u{1F357}", keywords: ["chicken", "meat"]),
        Entry(character: "\u{1F354}", keywords: ["burger", "hamburger"]),
        Entry(character: "\u{1F35F}", keywords: ["fries"]),
        Entry(character: "\u{1F355}", keywords: ["pizza"]),
        Entry(character: "\u{1F32D}", keywords: ["hotdog"]),
        Entry(character: "\u{1F32E}", keywords: ["taco"]),
        Entry(character: "\u{1F35C}", keywords: ["ramen", "noodles"]),
        Entry(character: "\u{1F363}", keywords: ["sushi"]),
        Entry(character: "\u{1F366}", keywords: ["ice cream"]),
        Entry(character: "\u{1F369}", keywords: ["donut"]),
        Entry(character: "\u{1F36A}", keywords: ["cookie"]),
        Entry(character: "\u{1F382}", keywords: ["cake", "birthday"]),
        Entry(character: "\u{1F370}", keywords: ["cake", "slice"]),
        Entry(character: "\u{1F36B}", keywords: ["chocolate"]),
        Entry(character: "\u{2615}", keywords: ["coffee"]),
        Entry(character: "\u{1F375}", keywords: ["tea"]),
        Entry(character: "\u{1F37A}", keywords: ["beer"]),
        Entry(character: "\u{1F377}", keywords: ["wine"]),

        // Travel / places
        Entry(character: "\u{2708}\u{FE0F}", keywords: ["airplane", "flight", "travel"]),
        Entry(character: "\u{1F697}", keywords: ["car"]),
        Entry(character: "\u{1F695}", keywords: ["taxi"]),
        Entry(character: "\u{1F68C}", keywords: ["bus"]),
        Entry(character: "\u{1F693}", keywords: ["police car"]),
        Entry(character: "\u{1F691}", keywords: ["ambulance"]),
        Entry(character: "\u{1F6B2}", keywords: ["bike", "bicycle"]),
        Entry(character: "\u{1F680}", keywords: ["rocket", "launch"]),
        Entry(character: "\u{26F5}", keywords: ["boat", "sailboat"]),
        Entry(character: "\u{1F6A2}", keywords: ["ship"]),
        Entry(character: "\u{1F682}", keywords: ["train"]),
        Entry(character: "\u{1F3E0}", keywords: ["house", "home"]),
        Entry(character: "\u{1F3E2}", keywords: ["office", "building"]),
        Entry(character: "\u{1F3F0}", keywords: ["castle"]),
        Entry(character: "\u{26F0}\u{FE0F}", keywords: ["mountain"]),
        Entry(character: "\u{1F3D6}\u{FE0F}", keywords: ["beach"]),
        Entry(character: "\u{1F30B}", keywords: ["volcano"]),

        // Sky / nature
        Entry(character: "\u{2600}\u{FE0F}", keywords: ["sun"]),
        Entry(character: "\u{26C5}", keywords: ["cloud", "partly sunny"]),
        Entry(character: "\u{2601}\u{FE0F}", keywords: ["cloud"]),
        Entry(character: "\u{1F327}\u{FE0F}", keywords: ["rain"]),
        Entry(character: "\u{26C8}\u{FE0F}", keywords: ["storm", "thunder"]),
        Entry(character: "\u{1F308}", keywords: ["rainbow"]),
        Entry(character: "\u{2744}\u{FE0F}", keywords: ["snow", "snowflake"]),
        Entry(character: "\u{2B50}", keywords: ["star"]),
        Entry(character: "\u{1F31F}", keywords: ["star", "sparkle"]),
        Entry(character: "\u{1F319}", keywords: ["moon"]),
        Entry(character: "\u{1F30D}", keywords: ["earth", "globe", "world"]),
        Entry(character: "\u{1F525}", keywords: ["fire", "hot", "lit"]),
        Entry(character: "\u{1F4A7}", keywords: ["water", "drop"]),
        Entry(character: "\u{1F30A}", keywords: ["wave", "ocean"]),
        Entry(character: "\u{1F333}", keywords: ["tree"]),
        Entry(character: "\u{1F334}", keywords: ["palm tree"]),
        Entry(character: "\u{1F335}", keywords: ["cactus"]),
        Entry(character: "\u{1F338}", keywords: ["blossom", "flower"]),
        Entry(character: "\u{1F33A}", keywords: ["hibiscus", "flower"]),
        Entry(character: "\u{1F33B}", keywords: ["sunflower"]),
        Entry(character: "\u{1F339}", keywords: ["rose", "flower"]),
        Entry(character: "\u{1F340}", keywords: ["clover", "luck"]),
        Entry(character: "\u{1F341}", keywords: ["leaf", "maple"]),

        // Objects / activities
        Entry(character: "\u{26BD}", keywords: ["soccer", "football"]),
        Entry(character: "\u{1F3C0}", keywords: ["basketball"]),
        Entry(character: "\u{1F3C8}", keywords: ["football", "american"]),
        Entry(character: "\u{26BE}", keywords: ["baseball"]),
        Entry(character: "\u{1F3BE}", keywords: ["tennis"]),
        Entry(character: "\u{1F3AF}", keywords: ["target", "dart"]),
        Entry(character: "\u{1F3AE}", keywords: ["game", "controller"]),
        Entry(character: "\u{1F3A7}", keywords: ["headphones", "music"]),
        Entry(character: "\u{1F3B8}", keywords: ["guitar", "music"]),
        Entry(character: "\u{1F3B9}", keywords: ["piano", "music"]),
        Entry(character: "\u{1F3A8}", keywords: ["art", "palette"]),
        Entry(character: "\u{1F3AC}", keywords: ["movie", "film"]),
        Entry(character: "\u{1F4F7}", keywords: ["camera", "photo"]),
        Entry(character: "\u{1F4F1}", keywords: ["phone", "mobile"]),
        Entry(character: "\u{1F4BB}", keywords: ["laptop", "computer"]),
        Entry(character: "\u{231A}", keywords: ["watch", "time"]),
        Entry(character: "\u{1F4A1}", keywords: ["idea", "lightbulb"]),
        Entry(character: "\u{1F511}", keywords: ["key"]),
        Entry(character: "\u{1F512}", keywords: ["lock"]),
        Entry(character: "\u{1F514}", keywords: ["bell", "notification"]),
        Entry(character: "\u{1F4CC}", keywords: ["pin"]),
        Entry(character: "\u{1F4CE}", keywords: ["paperclip"]),
        Entry(character: "\u{2702}\u{FE0F}", keywords: ["scissors"]),
        Entry(character: "\u{1F4DD}", keywords: ["note", "write"]),
        Entry(character: "\u{1F4DA}", keywords: ["books"]),
        Entry(character: "\u{1F4B0}", keywords: ["money", "bag"]),
        Entry(character: "\u{1F48E}", keywords: ["gem", "diamond"]),

        // Symbols
        Entry(character: "\u{2705}", keywords: ["check", "done", "ok"]),
        Entry(character: "\u{274C}", keywords: ["cross", "no", "cancel"]),
        Entry(character: "\u{26A0}\u{FE0F}", keywords: ["warning", "alert"]),
        Entry(character: "\u{2753}", keywords: ["question"]),
        Entry(character: "\u{2757}", keywords: ["exclamation"]),
        Entry(character: "\u{2795}", keywords: ["plus", "add"]),
        Entry(character: "\u{2796}", keywords: ["minus", "subtract"]),
        Entry(character: "\u{267B}\u{FE0F}", keywords: ["recycle"]),
        Entry(character: "\u{2728}", keywords: ["sparkles"]),
        Entry(character: "\u{1F389}", keywords: ["party", "celebrate"]),
        Entry(character: "\u{1F3C6}", keywords: ["trophy", "award"]),
        Entry(character: "\u{1F947}", keywords: ["medal", "first"]),
        Entry(character: "\u{1F6A9}", keywords: ["flag"]),
        Entry(character: "\u{1F3F3}\u{FE0F}", keywords: ["flag", "white"]),
    ]
}
